//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehist_erp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ehist_erp()
        {
            this.Lignes = new HashSet<lhist_erp>();
        }
    
        public string NumMAJ { get; set; }
        public Nullable<System.DateTime> datemaj { get; set; }
        public string heuremaj { get; set; }
        public string codeapp { get; set; }
        public string libmaj { get; set; }
        public string codeutil { get; set; }
        public string nomutil { get; set; }
        public string codepv { get; set; }
        public string codemvt { get; set; }
        public Nullable<System.DateTime> datemvt { get; set; }
        public string typemvt { get; set; }
        public Nullable<double> MHT { get; set; }
        public Nullable<double> MTTC { get; set; }
        public Nullable<double> MTVA { get; set; }
        public Nullable<double> MREMISE { get; set; }
        public Nullable<double> MFODEC { get; set; }
        public Nullable<double> MRETENUE { get; set; }
        public string numpiece { get; set; }
        public string TYPEREGL { get; set; }
        public string CODETRS { get; set; }
        public string LIBTRS { get; set; }
        public string TYPETRS { get; set; }
        public string etat { get; set; }
        public string numdoss { get; set; }
        public string typefac { get; set; }
        public Nullable<double> cours { get; set; }
        public string codesel { get; set; }
        public string typemvtimp { get; set; }
        public Nullable<System.DateTime> datepiece { get; set; }
        public Nullable<double> mtdev { get; set; }
        public string declaration { get; set; }
        public string typdec { get; set; }
        public Nullable<System.DateTime> dateentree { get; set; }
        public string dae { get; set; }
        public string pieceliee2 { get; set; }
        public string devise { get; set; }
        public string dureeajout { get; set; }
        public string dureemodif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lhist_erp> Lignes { get; set; }
    }
}
