//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fournisseur
    {
        public string code { get; set; }
        public Nullable<System.DateTime> datec { get; set; }
        public string rsoc { get; set; }
        public string adresse { get; set; }
        public string adresse1 { get; set; }
        public string activite { get; set; }
        public string coder { get; set; }
        public string cp { get; set; }
        public string responsable1 { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string telex { get; set; }
        public string codes { get; set; }
        public string pays { get; set; }
        public string nature { get; set; }
        public string banque { get; set; }
        public string compteb { get; set; }
        public double remise { get; set; }
        public string comptec { get; set; }
        public string typreg { get; set; }
        public string matriculef { get; set; }
        public string commentaire { get; set; }
        public Nullable<double> MTDEBIT { get; set; }
        public Nullable<double> MTCREDIT { get; set; }
        public Nullable<double> SOLDEINI { get; set; }
        public Nullable<double> Solde { get; set; }
        public string gsm1 { get; set; }
        public string gsm2 { get; set; }
        public string responsable2 { get; set; }
        public string blockage { get; set; }
        public string responsable3 { get; set; }
        public string gsm3 { get; set; }
        public string titre1 { get; set; }
        public string titre2 { get; set; }
        public string titre3 { get; set; }
        public string nposte1 { get; set; }
        public string nposte2 { get; set; }
        public string nposte3 { get; set; }
        public string desisec { get; set; }
        public string desireg { get; set; }
        public string desicp { get; set; }
        public Nullable<double> srisque { get; set; }
        public Nullable<double> scredit { get; set; }
        public string coderep { get; set; }
        public string desrep { get; set; }
        public Nullable<double> totregle { get; set; }
        public Nullable<double> livcours { get; set; }
        public string comptecharge { get; set; }
        public Nullable<int> delaisreg { get; set; }
        public string typfrs { get; set; }
        public Nullable<double> soldeinidevise { get; set; }
        public string usera { get; set; }
        public string userm { get; set; }
        public string users { get; set; }
        public Nullable<System.DateTime> datemaj { get; set; }
        public Nullable<double> soldeinibe { get; set; }
        public Nullable<double> soldebe { get; set; }
        public Nullable<double> sdinilivencours { get; set; }
        public string genGPAO { get; set; }
        public string codedep { get; set; }
        public string codepv { get; set; }
        public string comptec2 { get; set; }
        public Nullable<double> soldeinied { get; set; }
        public string decision { get; set; }
        public Nullable<System.DateTime> datedebaut { get; set; }
        public Nullable<System.DateTime> datefinaut { get; set; }
    }
}
