//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SocieteEntities : DbContext
    {
        public SocieteEntities(string connectionString)
    : base(connectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<depot> depot { get; set; }
        public virtual DbSet<famille> famille { get; set; }
        public virtual DbSet<fournisseur> fournisseur { get; set; }
        public virtual DbSet<invphysique> invphysique { get; set; }
        public virtual DbSet<lignedepot> lignedepot { get; set; }
        public virtual DbSet<linv> linv { get; set; }
        public virtual DbSet<pointvente> pointvente { get; set; }
        public virtual DbSet<tmplignedepot> tmplignedepot { get; set; }
        public virtual DbSet<utilisateurpv> utilisateurpv { get; set; }
        public virtual DbSet<ehist_erp> ehist_erp { get; set; }
        public virtual DbSet<lhist_erp> lhist_erp { get; set; }
    }
}
