//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class invphysique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invphysique()
        {
            this.LignesInventaire = new HashSet<linv>();
        }
    
        public string numinv { get; set; }
        
        public Nullable<System.DateTime> dateinv { get; set; }
        public Nullable<int> nbrcomptage { get; set; }
        public string commentaire { get; set; }
        public string cloture { get; set; }
        public Nullable<System.DateTime> datecloture { get; set; }
        public string utilisateur { get; set; }
        public string coderep { get; set; }
        public string rsrep { get; set; }
        public string usera { get; set; }
        public string userm { get; set; }
        public string users { get; set; }
        public Nullable<System.DateTime> DATEDMAJ { get; set; }
        public string codepv { get; set; }
        public string libpv { get; set; }
        public string codedep { get; set; }
        public string libdep { get; set; }
        public string numcloture { get; set; }
        public Nullable<System.DateTime> dateimp { get; set; }
        public string typdec { get; set; }
        public string declaration { get; set; }
        public string typeapp { get; set; }
        public string zone { get; set; }
    
        public virtual pointvente PointVente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linv> LignesInventaire { get; set; }
        public virtual depot Depot { get; set; }
    }
}
