//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lhist_erp
    {
        public string nummaj { get; set; }
        public string CODEMVT { get; set; }
        public string typmvt { get; set; }
        public string CODEDEP { get; set; }
        public string LIBDEP { get; set; }
        public string CODEART { get; set; }
        public string DESART { get; set; }
        public Nullable<float> QTEART { get; set; }
        public Nullable<double> PRIX { get; set; }
        public Nullable<double> REMISEART { get; set; }
        public Nullable<double> TAUXMAJO { get; set; }
        public Nullable<float> TAUXTVA { get; set; }
        public string UNITE { get; set; }
        public Nullable<double> NBUNITE { get; set; }
        public string TYPEART { get; set; }
        public Nullable<double> TTFODEC { get; set; }
        public string FAMILLE { get; set; }
        public string codepv { get; set; }
        public string libpv { get; set; }
        public Nullable<double> prixvente { get; set; }
        public Nullable<double> marge { get; set; }
        public string pieceliee { get; set; }
        public string numseq { get; set; }
        public string touchestock { get; set; }
        public string conf { get; set; }
        public Nullable<double> qteliv { get; set; }
        public string Numdoss { get; set; }
        public Nullable<System.DateTime> datef { get; set; }
        public string ngp { get; set; }
        public Nullable<double> puartdev { get; set; }
        public Nullable<double> mtdt { get; set; }
        public Nullable<double> coef { get; set; }
        public Nullable<double> mttaxe { get; set; }
        public string coderep { get; set; }
        public string artfrs { get; set; }
        public Nullable<double> pvest { get; set; }
        public Nullable<System.DateTime> datderninv { get; set; }
        public Nullable<double> PXREV { get; set; }
        public string codeuser { get; set; }
    }
}
