//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public societe()
        {
            this.utilisateurs = new HashSet<utilisateurpv>();
        }
    
        public string code { get; set; }
        public string rsoc { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public string e1 { get; set; }
        public string e2 { get; set; }
        public string e3 { get; set; }
        public string e4 { get; set; }
        public string e5 { get; set; }
        public string e6 { get; set; }
        public string e7 { get; set; }
        public string e8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilisateurpv> utilisateurs { get; set; }
    }
}
