//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmplignedepot
    {
        public string famille { get; set; }
        public string codeart { get; set; }
        public string desart { get; set; }
        public Nullable<double> qteart { get; set; }
        public string lieustock { get; set; }
        public Nullable<System.DateTime> Datderninv { get; set; }
        public string codesel { get; set; }
        public string saisie { get; set; }
        public string LibUtil { get; set; }
        public string fourn { get; set; }
        public string libellefourn { get; set; }
        public Nullable<double> numordre { get; set; }
        public string codedep { get; set; }
        public string libelle { get; set; }
        public string nordre { get; set; }
        public Nullable<System.DateTime> dateexp { get; set; }
        public string numinv { get; set; }
        public Nullable<double> puht { get; set; }
        public sbyte isSelected { get; set; }
        public string codepv { get; set; }
        public Nullable<double> qteInventaire { get; set; }
        public string commentaire { get; set; }
    
        public virtual article Article { get; set; }
    }
}
